production:
  periodic_litestream_verification:
    class: Litestream::VerificationJob
    queue: default
    args: [ ]
    schedule: at 1am every day
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
